main/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='home'),
    path('terms/', views.policy, name='policy'),
    path('about/', views.about, name='about'),
]

smartshuk/urls.py
from django.contrib import admin
from django.urls import path, include

from main.views import page_404

urlpatterns = [
    path('admin-mode/', admin.site.urls),
    path('', include('main.urls')),
    path('', include('user.urls')),
    path('', include('user_ads.urls')),
    path('', include('mapping_app.urls')),
    path('', include('honeypot.urls')),
    path('404/', page_404, name='404'), # for debag mode test by enter www.site.com/404
]
handler404 = 'main.views.handler404'

from django.conf import settings
from django.conf.urls.static import static
from .settings import DEV_MODE
if DEV_MODE:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


from django.views.static import serve
from django.urls import re_path

urlpatterns += [
    re_path(r'^robots\.txt$', serve, {'document_root': settings.BASE_DIR, 'path': "/robots.txt"}),
]

user_ads/urls.py
from django.urls import path, include
from . import views

urlpatterns = [
    path('real_estate/', views.real_estate, name="real_estate"),
    path('real_estate_post/', views.real_estate_post, name="real_estate_post"),
    path('real_estate_delete/<int:pk>/', views.real_estate_delete, name='real_estate_delete'),
    path('real_estate/<int:pk>/', views.real_estate_detail, name='real_estate_detail'),
    path('real_estate/liked_real_estate_ids_json/', views.liked_real_estate_ids_json, name='liked_real_estate_ids_json'),
    path('real_estate/like/<int:real_estate_id>/', views.real_estate_like, name='real_estate_like'),

    path('secondhand/', views.secondhand, name="secondhand"),
    path('secondhand_post/', views.secondhand_post, name="secondhand_post"),
    path('secondhand_delete/<int:pk>/', views.secondhand_delete, name='secondhand_delete'),
    path('secondhand/<int:pk>/', views.secondhand_detail, name='secondhand_detail'),
    path('secondhand/liked_secondhand_ids_json/', views.liked_secondhand_ids_json, name='liked_secondhand_ids_json'),
    path('secondhand/like/<int:secondhand_id>/', views.secondhand_like, name='secondhand_like'),

    # page of new post section selection
    path('new_ad/', views.new_ad, name="new_ad"),
    # get child model instances for new post section by parent model
    path('get_subcategories_of_secondhand/<int:category_id>/', views.GetSubcategoriesOfSecondhand.as_view(), name='get_subcategories_of_secondhand'),
    path('get_type_of_secondhand/<int:sub_category_id>/', views.GetTypeOfSecondhand.as_view(), name='get_type_of_secondhand'),
    
]

user_ads/models.py
from django.db import models
from django.urls import reverse
from location_field.models.plain import PlainLocationField
import datetime
from datetime import date
from django.core.validators import MaxValueValidator, MinValueValidator
from smartshuk.settings import AUTH_USER_MODEL, MEDIA_URL, VALID_IMAGE_EXTENSIONS, DATA_UPLOAD_MAX_MEMORY_SIZE
# image processing
from own_libs import image_processing
from PIL import Image, ImageOps
import os
from django.core.validators import RegexValidator
from django.core.validators import FileExtensionValidator
from django.core.exceptions import ValidationError
from user.models import CustomUser
from django.core.files.storage import default_storage
import uuid
from django.utils import timezone
from io import BytesIO
from django.core.files.base import ContentFile
from pillow_heif import register_heif_opener
# delete multiple objects
from django.db.models.signals import pre_delete, post_delete
from django.dispatch import receiver

register_heif_opener()


def validate_file_size(value):
    if value.size > DATA_UPLOAD_MAX_MEMORY_SIZE:
        raise ValidationError(f"גודל הקובץ חייב להיות לא יותר מ {DATA_UPLOAD_MAX_MEMORY_SIZE // (1024 * 1024)} MB.")




class Ad(models.Model):
    id = models.AutoField(primary_key=True)
    picture = models.ImageField(    blank=False,
                                    max_length= 500, # 100 
                                    verbose_name='תמונה ראשית',
                                    validators=[
                                            FileExtensionValidator(allowed_extensions=VALID_IMAGE_EXTENSIONS),
                                            validate_file_size,
                                        ],
                                )
    has_album = models.BooleanField(blank=True, default=False) # delete this field
    
    author = models.ForeignKey(AUTH_USER_MODEL, on_delete=models.CASCADE)
    date = models.DateTimeField(auto_now_add=True, blank=True,)
    title = models.CharField(verbose_name='כותרת', max_length=50, blank=True)
    description = models.TextField(verbose_name='תיאור (טקסט חופשי)', max_length=1000, blank=True)

    # phone_regex = RegexValidator(
    #     regex=r'^\+?1?\d{9,15}$',
    #     # message="Phone number must be entered in the format: '972520000000+ or '0540000000. Up to 15 digits allowed."
    #     message="מספר הטלפון חייב להיכנס בפורמט: '+972520000000 או '0540000000. עד 15 ספרות מותרות."
    # )
    phone_regex = RegexValidator(
        regex=r'^\+?1?[\d\s-]{9,15}$',
        message="מספר הטלפון חייב להיכנס בפורמט: 97252-0000000+ או 0520000000 עד 15 ספרות, רווחים ומקפים מותרים."
    )


    phone = models.CharField(validators=[phone_regex], verbose_name='טלפון', max_length=17, blank=True)
    
    class Meta:
        abstract = True #Cannot create instances of that model directly
    
    # chek for floor < house and ather...
    #!ADD!# limit on format, archive and size when uploading
    def save(self, *args, **kwargs):
        if self.picture:
            if self.pk:
                current_obj = self.__class__.objects.get(pk=self.pk)
                if current_obj.picture != self.picture:
                    current_obj.picture.delete(save=False)

            unique_id = uuid.uuid4().hex
            timestamp = timezone.now().strftime("%Y-%m-%d_%H-%M-%S")
            new_filename = f"{timestamp}_{unique_id}.jpg"

            self.picture.field.upload_to = f'media/user-uploads/{self.__class__.__name__}'

            img = Image.open(self.picture)
            if img.mode == 'RGBA':
                img = img.convert('RGB')
            img = ImageOps.exif_transpose(img)
            max_px = 800
            if img.width > max_px or img.height > max_px:
                img.thumbnail((max_px, max_px))

            buffer = BytesIO()
            img.save(buffer, format='JPEG')
            buffer.seek(0)

            self.picture.save(new_filename, ContentFile(buffer.read()), save=False)

        super().save(*args, **kwargs)


    #chack box on Delete not work!!! add signals
    def delete(self, *args, **kwargs):
        #delete avatar
        # print(f"Delete: avatar: {self.picture}")
        try:
            # Delete the object from S3
            key = f'{self.picture}'
            if default_storage.exists(key):
                default_storage.delete(key)
                #print(f"Deleted: {key}")
            else:
                #print(f"File not found: {key}")
                pass
                    
        except Exception as e:
            #print(f"Exception while deleting the picture: {e}")
            pass
        super().delete(*args, **kwargs)

class Region(models.Model):
    """List of Region options"""
    name = models.CharField(max_length=100)

    class Meta:
        verbose_name = 'Region'
        verbose_name_plural = 'Regions'
        ordering = ['name']

    def __str__(self):
        return self.name

class City(models.Model):
    """List of Cities options"""
    region = models.ForeignKey(Region, on_delete=models.CASCADE)

    name = models.CharField(max_length=100)

    class Meta:
        verbose_name = 'City'
        verbose_name_plural = 'Cities'
        ordering = ['name']

    def __str__(self):
        return self.name

class Brand(models.Model): # for all Searching and Filtering (New and SecondHand things)
    # list of SecondHand brands (Samsung, LG, etc). Only for Admin Panel
    name = models.CharField(verbose_name='Brand', max_length=100)
    singular_name = models.CharField(verbose_name='Singular name of brand', max_length=100, blank=True)

    class Meta:
        verbose_name = 'Brand'
        verbose_name_plural = 'Brands'
        ordering = ['name']
    
    def __str__(self):
        return self.name

##########################################
#       Next code is about RealEstate    #
##########################################

class RealEstateCategory(models.Model):
    """List of RealEstate options (New Home, Apartments for rent, Garag, Commercial, Etc). Only for Admin Panel"""
    name = models.CharField(verbose_name='Real estate category', max_length=100)
    singular_name = models.CharField(verbose_name='Real estate singular name of category', max_length=100, blank=True)

    class Meta:
        verbose_name = 'Real estate category'
        verbose_name_plural = 'Real estate categories'
        ordering = ['-name']

    def __str__(self):
        return self.name

class RealEstateDeal(models.Model):  # for realEstate
    """List of Deal types (bay, rent, change ... etc"""
    name = models.CharField(verbose_name='Real estate deal type', max_length=100)

    class Meta:
        verbose_name = 'Real estate deal type'
        verbose_name_plural = 'Real estate deal_types'
        ordering = ['-name']

    def __str__(self):
        return self.name

class RealEstate(Ad):
    #...
    category = models.ForeignKey(RealEstateCategory, verbose_name='קטגוריה', on_delete=models.CASCADE)
    deal_type = models.ForeignKey(RealEstateDeal, verbose_name='סוג העסקה', on_delete=models.CASCADE)
    city = models.ForeignKey(City, verbose_name='עיר', on_delete=models.CASCADE)
    #album = models.OneToOneField(ImageAlbum, on_delete=models.CASCADE)
    address = models.CharField(verbose_name='כתובת',max_length=255)
    cost = models.IntegerField(verbose_name='מחיר', validators=[MinValueValidator(0), MaxValueValidator(100000000)]) # -1 = auction
    rooms = models.SmallIntegerField(verbose_name='מספר חדרים', validators=[MinValueValidator(0), MaxValueValidator(100)])# 0 = studio
    floor = models.SmallIntegerField(verbose_name='קומה', validators=[MinValueValidator(-10), MaxValueValidator(100)])
    size_m2 = models.PositiveSmallIntegerField(verbose_name='שטח (במ״ר)', validators=[MinValueValidator(0), MaxValueValidator(1000)])
    number_floors_in_house = models.PositiveSmallIntegerField(verbose_name='מספר הקומות במבנה', validators=[MinValueValidator(1), MaxValueValidator(100)])
    CheckIn_date_from = models.DateField(verbose_name='תאריך כניסה', default=datetime.date.today, blank=True)

    is_new = models.BooleanField(verbose_name='הנכס חדש', default=False)
    renovated = models.BooleanField(verbose_name='לאחר שיפוץ', default=False)
    furnished = models.BooleanField(verbose_name='מרוהט', default=False)
    balcony = models.BooleanField(verbose_name='עם מרפסת', default=False)
    bunker = models.BooleanField(verbose_name='עם ממ"ד', default=False)
    storage = models.BooleanField(verbose_name='מחסן', default=False)
    conditioner = models.BooleanField(verbose_name='מזגן', default=False)
    elevator = models.BooleanField(verbose_name='מעלית', default=False)
    parking = models.BooleanField(verbose_name='חניה', default=False)
    water_heater = models.BooleanField(verbose_name='דוד שמש', default=False)
    disabled_access = models.BooleanField(verbose_name='גישה לנכים', default=False)
    # without_intermediaries = models.BooleanField(verbose_name='without intermediaries', default=False,)
    # verified seller
    exclusive = models.BooleanField(verbose_name='בלעדי', default=False)

    @property
    def is_past_due(self):
        return date.today() > self.CheckIn_date_from
    
    def delete(self, *args, **kwargs):
        # Delete all related pictures of album
        for picture in self.pictures.all():
            picture.delete()

        # Call the delete method of the parent class Ad
        super(RealEstate, self).delete(*args, **kwargs)

    class Meta:
        verbose_name ='Real estate' #'נדל"ן'
        verbose_name_plural = 'Real estate' #'נדל"ן'
        ordering = ['category', 'deal_type', 'city']

    def __str__(self):
        return self.category.name + ', ' + self.deal_type.name + ' : ' + self.city.name
    
class RealEstatePicture(models.Model):
    ad = models.ForeignKey(RealEstate, on_delete=models.CASCADE, related_name='pictures')
    picture = models.ImageField(upload_to = 'media/user-uploads/albums')

    class Meta:

user_ads/templates/user_ads/form_snippets/real_estate_form.html
<div class="search_wraper">
    {% include 'user_ads/form_snippets/ad_sections_titles.html' %}
    <div class="search_container">
        {{ form.category }}
        {{ form.deal_type }}
        {{ form.city }}
        <input class='field' type="submit" value="חיפוש" id='id_submit'>
    </div>
    {{ field.errors }}
    <div id="filters" class="filters">
        
        {% comment %} <div class="scroll_btn">
            < >
        </div> {% endcomment %}
        
        <span class="filter">
            {{ form.max_cost }}
            <span class="title">מחיר עד</span>
        </span>

        <div class="wrap_slider">
            <div class="slider" id="slider-distance">
                
                <div>
                    <div inverse-left style="width:70%;"></div>
                    <div inverse-right style="width:70%;"></div>
                    <div range style="left:0%;right:0%;"></div>
                    <span thumb style="left:0%;"></span>
                    <span thumb style="left:100%;"></span>
                    
                    <div sign style="left:0%;">
                        <span id="value">0</span>
                    </div>
                    
                    <div sign >
                        <span id="value">6</span>
                    </div>

                    <span 
                        style="
                        position: absolute;
                        right: -15px;
                        top: -9.5px;
                        font-size: 20px;
                        color: #111;"
                        >
                        +
                    </span>

                </div>
                {{ form.min_rooms }}
                {{ form.max_rooms }}        
                <script>    
                    var min_rooms = document.getElementById("id_min_rooms")
                    min_rooms.value = Math.min(min_rooms.value,min_rooms.parentNode.childNodes[5].value-1);
                    var value=(100/(parseInt(min_rooms.max)-parseInt(min_rooms.min)))*parseInt(min_rooms.value)-(100/(parseInt(min_rooms.max)-parseInt(min_rooms.min)))*parseInt(min_rooms.min);
                    var children = min_rooms.parentNode.childNodes[1].childNodes;
                    children[1].style.width=value+'%';
                    children[5].style.left=value+'%';
                    children[7].style.left=value+'%';children[11].style.left=value+'%';
                    children[11].childNodes[1].innerHTML=min_rooms.value;
                    
                    var max_rooms = document.getElementById("id_max_rooms")
                    max_rooms.value = Math.max(max_rooms.value,max_rooms.parentNode.childNodes[3].value-(-1));
                    var value=(100/(parseInt(max_rooms.max)-parseInt(max_rooms.min)))*parseInt(max_rooms.value)-(100/(parseInt(max_rooms.max)-parseInt(max_rooms.min)))*parseInt(max_rooms.min);
                    var children = max_rooms.parentNode.childNodes[1].childNodes;
                    children[3].style.width=(100-value)+'%';
                    children[5].style.right=(100-value)+'%';
                    children[9].style.left=value+'%';children[13].style.left=value+'%';
                    children[13].childNodes[1].innerHTML=max_rooms.value;
                </script>

                <script>
                    {% comment %} script that will add a no-scroll class to the #filters element when the slider is being interacted with {% endcomment %}
                    var slider = document.querySelector('.wrap_slider');
                
                    slider.addEventListener('touchstart', function(e) {
                        e.stopPropagation();
                        document.querySelector('#filters').classList.add('no-scroll');
                    });
                
                    slider.addEventListener('touchend', function() {
                        document.querySelector('#filters').classList.remove('no-scroll');
                    });
                
                    //$(document).ready(function() {
                    //    $(".slider input[type=range]").on("mousedown touchstart", function(e) {
                    //        e.stopPropagation();
                    //        document.querySelector('#filters').classList.add('no-scroll');
                    //    });
                    //    $(".slider input[type=range]").on("mouseup touchend", function() {
                    //        document.querySelector('#filters').classList.remove('no-scroll');
                    //    });
                    //});
                </script>
            </div>
            <span class="title">מספר חדרים</span>
            
        </div>

        {% comment %} https://stackoverflow.com/questions/19206919/how-to-create-checkbox-inside-dropdown {% endcomment %}

        <span class="filter toggle">
            {{ form.is_new }}
            <label for="id_is_new"></label>
            <span class="title">בניין חדש</span>
        </span>
        
        <span class="filter toggle">
            {{ form.renovated }}
            <label for="id_renovated"></label>
            <span class="title">משופץ</span>
        </span>

        <span class="filter toggle">
            {{ form.furnished }}
            <label for="id_furnished"></label>
            <span class="title">מרוהט</span>
        </span>
        
        <span class="filter toggle">
            {{ form.balcony }}
            <label for="id_balcony"></label>
            <span class="title">מרפסת</span>
        </span>
        
        <span class="filter toggle">
            {{ form.bunker }}
            <label for="id_bunker"></label>
            <span class="title">ממ״ד</span>
        </span>

        <span class="filter toggle">
            {{ form.storage }}
            <label for="id_storage"></label>
            <span class="title">מחסן</span>
        </span>

        <span class="filter toggle">
            {{ form.conditioner }}
            <label for="id_conditioner"></label>
            <span class="title">מזגן</span>
        </span>

        <span class="filter toggle">
            {{ form.elevator }}
            <label for="id_elevator"></label>
            <span class="title">מעלית</span>
        </span>
        
        <span class="filter toggle">
            {{ form.parking }}
            <label for="id_parking"></label>
            <span class="title">חניה</span>
        </span>
        
        <span class="filter toggle">
            {{ form.disabled_access }}
            <label for="id_disabled_access"></label>
            <span class="title">גישה לנכים</span>
        </span>
        
        {% comment %} <span class="filter toggle">
            {{ form.without_intermediaries }}
            <label for="id_without_intermediaries"></label>
            <span class="title">ללא מתווך</span>
        </span> {% endcomment %}
        
        <span class="filter toggle">
            {{ form.with_phote_only_toggle }}
            <label for="id_with_phote_only_toggle"></label>
            <span class="title">עם תמונה</span>
        </span>
        
        <span class="filter toggle">
            {{ form.exclusive }}
            <label for="id_exclusive"></label>
            <span class="title">בבלעדיות</span>
        </span>
        




        {% comment %} <span class="filter">
            {% include  "../module/range_slider.html"%}
            <span class="title">מספר חדרים</span>
        </span> {% endcomment %}
        
        
    </div>
    <br>
<div>